server:
  port: 8000

spring:
  application:
    name: restful-db

  # MomngoDB
  data:
    mongodb:
      uri: mongodb://root:root@localhost:37017/library?authSource=admin&authMechanism=SCRAM-SHA-1
#      host: localhost
#      port: 37017
#      database: library
#      username: root
#      password: root
#      write-concern: NORMAL

  # MySQL Database access configuration properties via JDBC
  datasource:
    url: jdbc:mysql://localhost:4306/library
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate configuration properties
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Flyway configuration
  flyway:
    locations:
      classpath: db/migration