version: '3.8'  # Use the latest version of Docker Compose syntax

services:
  mongo:
    image: mongo:latest  # Use the latest MongoDB image from Docker Hub
    container_name: mongo  # Name your container
    ports:
      - "37017:27017"  # Map container port 27017 to host port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Set a root username for Mongo
      MONGO_INITDB_ROOT_PASSWORD: root # Set a root password for Mongo
    volumes:
      - mongodb_data:/data/db  # Mount a volume for MongoDB data persistence
  mysql:
    image: mysql:latest  # Use the latest MySQL image from Docker Hub
    container_name: mysql  # Name your container
    ports:
      - "4306:3306"  # Map container port 3306 to host port 3306
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set a root password for MySQL
      MYSQL_DATABASE: library  # Create an initial database
      MYSQL_USER: usr  # Create a user
      MYSQL_PASSWORD: pwd  # Set a password for the user
    volumes:
      - mysql_data:/var/lib/mysql  # Mount a volume for MySQL data persistence

volumes:
  mongodb_data:  # Declare a volume for MongoDB data persistence
  mysql_data:  # Declare a volume for MySQL data persistence